title: Title of your CV site
profile_img: /assets/img/propic1.jpg
icon_img: /assets/img/icon.webp

name: "Aklima Khanam Lima"
job: "Physicist | Aspiring Data Scientist | Researcher"

#phone_number: 012-345-6789
address: Aurora, IL, USA
email: aklima@syr.edu
linkedin_username: aklima-khanam-492726148
github_username: aklimakhanam
instagram_username: aklima.khanam
#twitter_username: twitter
facebook_username: aklima.phy.du
#youtube_username: youtube
#blog_url: homepage-url
researchgate_username: Aklima-Khanam-Lima?ev=hdr_xprf
orcid_username: 0009-0008-0481-4606 

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl:

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
